### ISSUE TITLE
Host DFU application(s)

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/sln_voice#12]
Implement DFU host application for the STLP voice application.

**Comment by mbanth** [comment]
@keithm-xmos, what help do you want/need for this issue?  XVF3800 will need a host app too.  Perhaps some sharing is possible.

**Comment by keithm-xmos** [comment]
This issue is blocked by https://github.com/xmos/sln_voice/issues/10

**Comment by keithm-xmos** [comment]
WE are trying to use [dfu-util ](https://dfu-util.sourceforge.net/) as the host app.  @xmos-jmccarthy has verified it in Linux, now we need to verify it works OK with macOS and Windows 10 & 11.
