### ISSUE TITLE
Implement software restructuring so xcore_sdk is not a dependency

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/sln_voice#129]
- [x] Rename targets in fwk_rtos, fwk_io and fwk_core

- [x] sln_voice changes
  - [x]     Directly submodule contents of current xcore_sdk modules folder
  - [x]     Update target libraries
  - [x]     Verify all CI checks pass
- [x] fwk_core changes
  - [ ]     Fork lib_tflite_micro and provide a patched branch.  
  - [x]     Verify all CI checks pass
- [x] fwk_rtos changes
  - [x]     Relocate xcore_sdk rtos tests
  - [x]     Update CI to run tests
  - [x]     Verify all CI tests pass

- [ ] Rename xcore_sdk to explorer_board_sdk (name pending agreeance)
  - [ ]     Verify all CI checks pass

**Comment by xmos-jmccarthy** [comment]
All targets renamed.

fwk_core complete
https://github.com/xmos/fwk_core/pull/15

fwk_io pending on inferencing branch to allow tests to pass.
https://github.com/xmos/fwk_io/pull/48

fwk_rtos complete.
https://github.com/xmos/fwk_rtos/pull/92

sln_voice complete (docs not working currently)
https://github.com/xmos/sln_voice/pull/151

xcore_sdk pending official new name.  repo name, and some internal target names need to be updated to this new name.  My current proposed name is sln_explorer_board
https://github.com/xmos/xcore_sdk/pull/576

**Comment by xmos-jmccarthy** [comment]
lib_tflite_micro handled a different way per our discussion.  Removed from fwk_core, and fetch_content enabled in sln_voice directly.

**Comment by keithm-xmos** [comment]
Create issue for renaming xcore_sdk https://github.com/xmos/xcore_sdk/issues/577

Closing this issue as all other tasks are ticked off.
