### ISSUE TITLE
How-to documents

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/sln_voice#232]
Add How-To documents that could include:

- [x] How to modify the code for a hybrid USB/I2S architecture. i.e. USB output interface but taking reference signal from I2S
- [ ] How to add HID button
- [x] How to add a different speech recognition library
- [x] How to update VoiceHub model in low-power FFD example design
- [x] How to change sampling rate, bit resolution or number of input channels
- [ ] How to output raw mic signals

**Comment by keithm-xmos** [comment]
For "How to output raw mic signals"

xflash --factory example_ffva_verbose_output_test.xe  --boot-partition-size 0x100000 --data example_ffva_ua_adec_data_partition.bin

**Comment by mbanth** [comment]
This issue is now tracked in [Carried Enhancements](https://xmosjira.atlassian.net/wiki/spaces/TNPMS/pages/3870916609/Carried+Enhancements).  The checklist in the description here should still be used to track pieces of work remaining to be completed.
