### ISSUE TITLE
Documentation updates for v2.0.0

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/sln_voice#275]
- [x] Update FFD README
- [x] Update programming guide to reflect audio pipelines that are now in modules
- [x] Remove AVS setup instructions from Getting Started guide
- [x] Update FFD documentation 
     - [x] Available SRAM on tile[0] reduced by 58k of RTOS heap + additional code??  
- [x] Remove all references to Wanson ASR
- [x] Add low_power FFD documentation 
- [x] Add entry about Sensory license to programming guide
- [x] Instructions on using releases from GitHub (zips or checking out tags).  Add to Programming Guide and README
- [x] Add doc (with working example) for changing/updating low-power FFD Sensory model

**Comment by keithm-xmos** [comment]
@jcarrier-xmos switched the style of two of the low-power FFD diagrams that are related to ones also in FFD. If the style he went with is preferred, the same update could be applied to FFD.

**Comment by jcarrier-xmos** [comment]
Low power FFD does not have a `software_desc/asr.rst` (like ffd has, which is in need of updating) it is unclear how the `modules/asr` component is to be documented/linked to both FFD examples.

**Comment by jcarrier-xmos** [comment]
I noticed that the `Third-Party` section in the docs needs to be updated for Sensory
