### ISSUE TITLE
Add back USB adaptive tests

### ISSUE THREAD

**Issue by shuchitak** [xmos/sln_voice#294]
Add @ACascarino's Adaptive USB tests https://github.com/ACascarino/sln_voice/tree/804a66617eb5be8d9c54cc92157b219c949e113d/test/examples/stlp back into the the sln_voice.

**Comment by mbanth** [comment]
@shuchitak, please provide a Story Point value for this issue.  Thanks.

**Comment by mbanth** [comment]
This issue is now tracked in [Carried Enhancements](https://xmosjira.atlassian.net/wiki/spaces/TNPMS/pages/3870916609/Carried+Enhancements).
