### ISSUE TITLE
Create a ASRC demo example

### ISSUE THREAD

**Issue by shuchitak** [xmos/sln_voice#295]
Create a I2S Slave + pipeline example with the bclk and mclk in different clock domains and use the ASRC module to demonstrate sampling rate conversion when the input and output are in different clock domains.

**Comment by shuchitak** [comment]
My plan is to first create a simple application to do this:
![asrc_demo drawio](https://github.com/xmos/sln_voice/assets/38428600/4809c1be-9c61-4bec-b3b1-4c75ab582bfb)

**Comment by mbanth** [comment]
@shuchitak, please provide a Story Point value for this issue.  Thanks.

**Comment by mbanth** [comment]
This issue duplicates Jira [AP-87](https://xmosjira.atlassian.net/browse/AP-87).
