### ISSUE TITLE
STLP USB audio device no longer detected on Windows

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/sln_voice#78]
Release v0.10.0 works.  Unclear what commit between then and now broke it.  However, the USB descriptor was recently modified so look there.  

https://github.com/xmos/sln_voice/commit/cedada4ca02ce1aee332590f7229c0ae3e88e02b

**Comment by xmos-jmccarthy** [comment]
Device is detected, but does not configure correctly.

Closing, as superseded by #80
