### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/sln_voice#85]
**NOTE: This task, once committed, needs to be broken up into smaller tasks.**  

Need to develop and automate tests for the following features:

- Adaptive USB (Medium)
- [Sample rate conversion](https://github.com/xmos/sln_voice/issues/102)
- Audio pipeline (Small, just needs automating)
- I2S input/output
- USB input/output
- Speech recognition event output to host (Small-to-medium)
- Host SoC wake from stand-by from GPO or I2C​ (Small-to-medium)
- Host command fetching from UART or I2C​ (Small-to-medium)
- (more that might be unintentionally omitted)

Later:

- DFU (Small-to-medium)
- Audio output

**Comment by xmos-jmccarthy** [comment]
A pi alternative may be the aardvark.  This is a link to their C_api source:
https://www.totalphase.com/products/aardvark-software-api
