### ISSUE TITLE
Add support for diagnostic audio output to non-USB applications/configurations

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/sln_voice#94]
Would include processed audio outputs and potentially pipeline intermediate outputs.  

Would apply to:

- FFD
- STLP-INT

Output options might be:

- SPI
- Packed I2S

Document how to enable this diagnostic mode.

**Comment by mbanth** [comment]
THis issue is now tracked in [Carried Enhancements](https://xmosjira.atlassian.net/wiki/spaces/TNPMS/pages/3870916609/Carried+Enhancements).
